version: '3.9'
services:
  servidor:
  build: "./Server_python"
  image: "calculadora_servidor"
  ports:
    - "9090:9090"
  networks:
    redCalculadora:
      ipv4_address: 172.24.2.1
  
  cliente:
    build: "./Cliente_java"
    image: "calculadora_cliente"
    networks:
      redCalculadora:
        ipv4_address: 172.24.2.2
    command: java -cp ./lib/libthrift-0.13.0.jar:./lib/slf4j-api-1.7.30.jar:./lib/slf4j-nop-1.7.30.jar:./lib/javax.annotation-api-1.3.2.jar:./gen-java:. ClienteCalculadora 172.24.2.1 9090

networks:
  redCalculadora:
  name: eder_ivan
  driver: bridge
  ipam:
    driver: default
    config:
      - subnet: "172.24.2.0/16"